name: Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installs the app's dependencies from the requirements file

    - name: Install NLTK data
      run: |
        python -m nltk.downloader punkt  # Download required NLTK data

    - name: Run Streamlit app
      run: |
        streamlit run app.py --server.port 8501 --server.address 0.0.0.0  # Run the Streamlit app
      env:
        HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}  # Add any necessary environment variables
